routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ROUTE PAR DEFAUT
// PATTERN : /
// CTRL : PagesController
// ACTION : Show

  Route::get('/', 'PagesController@show')->defaults('page', 1)->name('homepage');

// ROUTE DU DETAIL D'UNE PAGE
// PATTERN : /pages/id/slug.html
// CTRL : PagesController
// ACTION : Show

  Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
  ->where(['page' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('pages.show');

// ROUTE DES PROJETS

  Route::prefix('projets')->name('projets.')->group(function () {

  // ROUTE DU DETAIL D'UN PROJET
  // PATTERN : /projets/id/slug.html
  // CTRL : ProjetsController
  // ACTION : Show

    Route::get('{projet}/{slug}.html', 'ProjetsController@show')
    ->where(['projet' => '[1-9][0-9]*',
             'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
    ->name('show');

  // ROUTE AJAX DU CHARGEMENT DES ANCIENS PROJETS
  // PATTERN : /projets/older.html
  // CTRL : ProjetsController
  // ACTION : ajaxOlder

    Route::get('older.html', 'ProjetsController@ajaxOlder')->name('ajax.older');
  });


// ROUTE DES POSTS

  Route::prefix('posts')->name('posts.')->group(function () {

  // ROUTE DU DETAIL D'UN POST
  // PATTERN : /posts/id/slug.html
  // CTRL : PostsController
  // ACTION : Show

    Route::get('{post}/{slug}.html', 'PostsController@show')
    ->where(['post' => '[1-9][0-9]*',
             'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
    ->name('show');

  // ROUTE DU FLUX RSS DES POSTS
  // PATTERN : /posts/rss.html
  // CTRL : PostsController
  // ACTION : rss

    Route::get('rss', 'PostsController@feed')->name('rss');
  });

// ROUTE DU DETAIL D'UNE CATEGORIE
// PATTERN : /categories/id/slug.html
// CTRL : CategoriesController
// ACTION : Show

  Route::get('/categories/{categorie}/{slug}.html', 'categoriesController@show')
  ->where(['categorie' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('categories.show');

// ROUTE DU DETAIL D'UN TAG
// PATTERN : /tags/id/slug.html
// CTRL : TagsController
// ACTION : Show

   Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
   ->where(['tag' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
   ->name('tags.show');

resources/views/template/partials/_contact.blade.php
{{--
  ./resources/views/template/partials/_contact.blade.php
 --}}

 <div class="section section-map">
   <div class="col-sm-12" style="padding:0;">
     <!-- Map -->
     <div id="contact-us-map">
       <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
       <br />
       <small>
         <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
       </small>
       </iframe>
     </div>
     <!-- End Map -->
   </div>
 </div>
 <div class="section">
   <div class="container">
     <div class="row">
       <h3>Get in Touch with Us</h3>
       </hr>
       <div class="col-sm-6">
         <!-- Contact Info -->
         <p class="contact-us-details">
           <b>Address:</b> 123 Fake Street, LN1 2ST, London, United Kingdom<br/>
           <b>Phone:</b> +44 123 654321<br/>
           <b>Fax:</b> +44 123 654321<br/>
           <b>Email:</b> <a href="mailto:getintoutch@yourcompanydomain.com">getintoutch@yourcompanydomain.com</a>
         </p>
         <!-- End Contact Info -->
       </div>
       <div class="col-sm-6"></div>
     </div>
   </div>
 </div>

resources/views/template/partials/_footer.blade.php
{{--
  ./resources/views/template/partials/_footer.blade.php
 --}}


<div class="footer">
  <div class="container">

    <div class="row">

      <div class="col-footer col-md-4 col-xs-6">
        <h3>Contact Us</h3>
        <p class="contact-us-details">
            <b>Address:</b> 123 Downtown Avenue, Manhattan, New York, United States of America<br/>
            <b>Phone:</b> +1 123 45678910<br/>
            <b>Fax:</b> +1 123 45678910<br/>
            <b>Email:</b> <a href="mailto:info@yourcompanydomain.com">info@yourcompanydomain.com</a>
          </p>
      </div>
      <div class="col-footer col-md-4 col-xs-6">
        <h3>Our Social Networks</h3>
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam.</p>
        <div>
          <img src="{{ asset('img/icons/facebook.png') }}" width="32" alt="Facebook">
          <img src="{{ asset('img/icons/twitter.png') }}" width="32" alt="Twitter">
          <img src="{{ asset('img/icons/linkedin.png') }}" width="32" alt="LinkedIn">
          <a href="{{ route('posts.rss') }}"><img src="{{ asset('img/icons/rss.png') }}" width="32" alt="RSS Feed"></a>
      </div>
      </div>
      <div class="col-footer col-md-4 col-xs-6">
        <h3>About Our Company</h3>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci.</p>
      </div>

    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="footer-copyright">&copy; 2014 <a href="http://www.vactualart.com/portfolio-item/basica-a-free-html5-template/">Basica</a> Bootstrap HTML Template. By <a href="http://www.vactualart.com">Vactual Art</a>
        | <a href="{{ asset('./admin') }}">Login</a></div>

        </div>
      </div>
    </div>
  </div>
</div>

resources/views/template/partials/_head.blade.php
{{--
  ./resources/views/template/partials/_head.blade.php
 --}}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>@yield('title')</title>

<!-- Bootstrap Core CSS -->
<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

<!-- Custom CSS -->
<link rel="stylesheet" href="{{ asset('css/main.css') }}">
<link href="{{ asset('css/custom.css') }}" rel="stylesheet">

<script src="{{ asset('//use.edgefonts.net/bebas-neue.js') }}"></script>

<!-- Custom Fonts & Icons -->
<link href='{{ asset('http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800') }}' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{{ asset('css/icomoon-social.css') }}">
<link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">

<script src="{{ asset('js/modernizr-2.6.2-respond-1.1.0.min.js') }}"></script>

resources/views/template/partials/_navigation.blade.php
{{--
  ./resources/views/template/partials/_navigation.blade.php
 --}}


<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ Route('homepage') }}"><img src="{{ asset('img/logo.png') }}" alt="Basica"></a>
        </div>
        <div class="collapse navbar-collapse">
          @include('pages._menu')
        </div>
    </div>
</header>
<!--/header-->

resources/views/template/partials/_scripts.blade.php
{{--
  ./resources/views/template/partials/_scripts.blade.php
 --}}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.9.1.min.js"><\/script>')</script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>

<!-- Scrolling Nav JavaScript -->
<script src="{{ asset('js/jquery.easing.min.js') }}"></script>
<script src="{{ asset('js/scrolling-nav.js') }}"></script>

@yield('scripts')